"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import {
  Rocket, Brain, Box, Heart, Shield, TrendingUp, Activity, RotateCcw, DollarSign, Zap,
} from "lucide-react";

const features = [
  { icon: Rocket, title: "Autonomous Deployment", description: "Push code and let AI deploy, configure, and optimize your entire infrastructure automatically." },
  { icon: Brain, title: "AI Repository Analysis", description: "AI analyzes your codebase to detect frameworks, dependencies, and optimal deployment strategies." },
  { icon: Box, title: "Kubernetes Automation", description: "Zero-config Kubernetes. Manifests, services, ingress, and networking generated by AI." },
  { icon: Heart, title: "Self-Healing Infrastructure", description: "AI detects failures, restarts pods, adjusts resources, and heals your deployments automatically." },
  { icon: Shield, title: "AI Security Layer", description: "Real-time threat detection, firewall automation, vulnerability scanning, and SSL management." },
  { icon: TrendingUp, title: "Automatic Scaling", description: "Predictive autoscaling powered by ML. Scale before traffic spikes hit, not after." },
  { icon: Activity, title: "Real-Time Monitoring", description: "Full observability with distributed tracing, custom metrics, and AI anomaly detection." },
  { icon: RotateCcw, title: "Autonomous Rollbacks", description: "AI detects failures and automatically rolls back to the last known healthy deployment." },
  { icon: DollarSign, title: "Cost Optimization", description: "AI identifies idle resources, right-sizes pods, and recommends savings across your cluster." },
  { icon: Zap, title: "Zero DevOps Required", description: "No YAML, no Dockerfiles, no CI/CD pipelines. From GitHub to production in one click." },
];

export function FeaturesSection() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, amount: 0.1 });

  return (
    <section ref={ref} className="py-24 px-4 relative" id="features">
      <div className="max-w-7xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={isInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }} className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            <span className="gradient-text">The Future</span> of Cloud Deployment
          </h2>
          <p className="text-foreground-muted text-lg max-w-2xl mx-auto">
            Everything you need to deploy, manage, and scale applications with autonomous AI intelligence.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ delay: i * 0.08, duration: 0.5 }}
              whileHover={{ y: -4, boxShadow: "0 0 20px hsla(217, 91%, 60%, 0.1)" }}
              className="glass rounded-xl p-6 group cursor-pointer transition-colors duration-300 hover:border-primary/20"
            >
              <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                <feature.icon size={24} className="text-primary" />
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">{feature.title}</h3>
              <p className="text-sm text-foreground-muted leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
