import hashlib
import json
import re
import os
from pathlib import Path
from typing import Any

def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9-]", "-", value.lower()).strip("-")[:40] or "zeroops-app"

def _render_internal_hcl(plan: dict[str, Any], project_name: str) -> str:
    artifact_plan = {
        "cloud": plan.get("cloud"),
        "region": plan.get("region_label") or plan.get("region"),
        "revision": plan.get("revision", 1),
        "components": [
            {
                "id": component.get("id"),
                "service": component.get("service"),
                "tier": component.get("tier"),
            }
            for component in plan.get("components", [])
            if isinstance(component, dict)
        ],
    }
    encoded_plan = json.dumps(artifact_plan, sort_keys=True, separators=(",", ":"))
    services = {str(item.get("service") or "") for item in plan.get("components", [])}
    blocks: list[str] = []

    if "Azure App Service" in services:
        blocks.append('''data "azurerm_service_plan" "application" {
  name                = var.app_service_plan_name
  resource_group_name = var.resource_group_name
}

resource "azurerm_linux_web_app" "application" {
  name                = "${local.project_slug}-${var.deployment_suffix}"
  location            = var.location
  resource_group_name = var.resource_group_name
  service_plan_id     = data.azurerm_service_plan.application.id
  https_only          = true

  identity { type = "SystemAssigned" }
  site_config {}
}''')

    if "Azure Container Apps" in services:
        blocks.append('''resource "azurerm_container_app_environment" "application" {
  name                = "${local.project_slug}-${var.deployment_suffix}-env"
  location            = var.location
  resource_group_name = var.resource_group_name
}

resource "azurerm_container_app" "application" {
  name                         = "${local.project_slug}-${var.deployment_suffix}"
  container_app_environment_id = azurerm_container_app_environment.application.id
  resource_group_name          = var.resource_group_name
  revision_mode                = "Single"

  identity { type = "SystemAssigned" }
  template {
    container {
      name   = "application"
      image  = var.container_image
      cpu    = 0.5
      memory = "1Gi"
    }
  }
}''')

    if "Azure Blob Storage" in services:
        blocks.append('''resource "azurerm_storage_account" "application" {
  name                     = substr(replace("st${local.project_slug}${var.deployment_suffix}", "-", ""), 0, 24)
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
}''')

    if "Azure Key Vault" in services:
        blocks.append('''data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "application" {
  name                       = substr("kv-${local.project_slug}-${var.deployment_suffix}", 0, 24)
  location                   = var.location
  resource_group_name        = var.resource_group_name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  soft_delete_retention_days = 7
  purge_protection_enabled   = true
}''')

    if "Application Insights" in services:
        blocks.append('''resource "azurerm_application_insights" "application" {
  name                = "${local.project_slug}-${var.deployment_suffix}-insights"
  location            = var.location
  resource_group_name = var.resource_group_name
  application_type    = "web"
}''')

    if "Virtual Network" in services:
        blocks.append('''resource "azurerm_virtual_network" "application" {
  name                = "${local.project_slug}-${var.deployment_suffix}-vnet"
  location            = var.location
  resource_group_name = var.resource_group_name
  address_space       = ["10.0.0.0/16"]
}''')

    if "Azure Database for PostgreSQL Flexible Server" in services or "PostgreSQL" in services:
        blocks.append('''resource "azurerm_postgresql_flexible_server" "application" {
  name                   = "${local.project_slug}-${var.deployment_suffix}-postgres"
  resource_group_name    = var.resource_group_name
  location               = var.location
  version                = "16"
  administrator_login    = var.postgresql_administrator_login
  administrator_password = var.postgresql_administrator_password
  sku_name               = "B_Standard_B1ms"
  storage_mb             = 32768
}''')

    return f'''# Generated by ZeroOps internal deployment engine. Never expose through the API.
terraform {{
  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }}
  }}
}}

provider "azurerm" {{
  features {{}}
}}

variable "resource_group_name" {{ type = string }}
variable "location" {{ type = string }}
variable "app_service_plan_name" {{ type = string }}
variable "deployment_suffix" {{ type = string }}
variable "container_image" {{
  type    = string
  default = null
}}
variable "postgresql_administrator_login" {{
  type    = string
  default = "zeroopsadmin"
}}
variable "postgresql_administrator_password" {{
  type      = string
  sensitive = true
  default   = null
}}

locals {{
  project_slug = "{_slug(project_name)}"
  architecture = jsondecode(<<PLAN
{encoded_plan}
PLAN
  )
}}

{chr(10).join(blocks)}
'''

def generate_terraform_files(plan: dict, project_name: str, target_dir: str) -> str:
    """Generate HCL configuration in the target directory and return the file path."""
    os.makedirs(target_dir, exist_ok=True)
    terraform_source = _render_internal_hcl(plan, project_name)
    file_path = os.path.join(target_dir, "main.tf")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(terraform_source)
    return file_path
