# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy Python app to Azure Web App - zeroops-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-backend-app
          path: |
            backend
            !backend/antenv/

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: python-backend-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_031835031AB3419FA6FDD8FF981F6AD6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0F96AE601A240DC8C4A9E99DFE9C71B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CD8A28758F2C46F3BAAA42043488CB5B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zeroops-backend'
          slot-name: 'Production'
          package: .
