# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy Python app to Azure Web App - zeroops-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean build virtual environment
        run: rm -rf backend/antenv

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-backend-app
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: python-backend-app
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_60ACB2A90AD54CD4964DB63073AEB479 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60AE222B23A4498E8C8D8B1406983EC2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16E28753469340139CFF339C6075F2D0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zeroops-backend'
          slot-name: 'Production'
          package: .
          startup-command: 'gunicorn -w 1 -k uvicorn.workers.UvicornWorker --timeout 180 main:app'
